# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: true

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

addons:
  apt:
    packages:
      - git
      - build-essential
      - libxml2-dev
      - libfftw3-dev
      - libmagickwand-dev
      - libopenexr-dev
      - liborc-0.4-0
      - gobject-introspection
      - libgsf-1-dev
      - libglib2.0-dev
      - liborc-0.4-dev
      - automake
      - libtool
      - swig
      - gtk-doc-tools

before_install:
  - set -e
  - git clone https://github.com/jcupitt/libvips.git
  - cd libvips
  - ./autogen.sh
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - rustup self update

install:
  - source ~/.cargo/env || true

script:
  - cargo build
  - cargo test
  - cargo doc && echo "<meta http-equiv=refresh content=0;url=`echo vips_rs | cut -d '/' -f 2`/index.html>" > target/doc/index.html

after_script: set +e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh
  keep_history: true
  local_dir: target/doc
  verbose: true
  on:
    branch: master

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never